### ISSUE TITLE
Test on Mac Please

### ISSUE THREAD

**Issue by Aska0526** [stephen-hqxu/superterrainplus#55]
### The issue

- [X] I could not find a similar issue and confirm this is a new feature.

### The limitation

Hi, your repo is fantastic and I love your work! Can you please transfer the framework to MacOS as well?

### The solution

Use Metal on Mac

**Comment by stephen-hqxu** [comment]
HI @Aska0526,

Thanks for your feedback and interest in this piece of work 😄 

The main issue that I can't test this on Mac is because I don't have access to a Mac machine and I don't know much about that OS. As you have suggested Metal and also noticed, this project heavily relies on vendor-specific OpenGL extensions for which Mac doesn't have access to.

As I personally don't have any experience with Metal and I am working on this project alone, it's quite beyond my capability and time allowance. I would like to focus on the current toolset rather than maintaining 2 different implementations and complicates the codebase. As I am using this library in my research, my goal is to deliver any feature I need as agile as I could, so having a simpler implementation helps me to keep everything on track.

Meanwhile, you can try to run it from either Windows or Linux as those are my primary working and testing environment.
